baseURL: https://20y.hu/~slink/
languageCode: en-us
defaultContentLanguage: en
title: Gabor Torok
theme: cupper-hugo-theme
enableGitInfo: false

taxonomies:
  tags: tags

permalinks:
  journal: /journal/:filename/

imaging:
  quality: 99

params:
  description:
  homeMetaContent: Contemplations on life
  footer: ■■■
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: false
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false
  navTitleText: ~slink/
  logoAlt: An alternative text description of the logo
  customCss:
    - css/custom.css
  #   - css/custom_02.css
  # customJs:
  #   - js/custom_01.js
  #   - js/custom_02.js

menu:
  nav:
    - name: Journal
      url: /journal/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: Blogroll
      url: /blogroll/
      weight: 3
    - name: Mixtapes
      url: /mixtapes/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
